# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Hadi Minooei's Blog!
description: This is my 2 cents for DS/AI/ML community. Feedback is always welcomed!
# github_username: hminooei

# Email and twitter are optional:
# email: hminooei@gmail.com
# twitter_username: dsbyhadi
author:
  name: Hadi Minooei
  email: hminooei@gmail.com

# Set this to true to get LaTeX math equation support
use_math: True

show_excerpts: True

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    twitter: dsbyhadi
    github: hminooei
    stackoverflow: "4245534"
    linkedin: hadi-minooei-23b50b22
    youtube_channel: UCuUos05DqrTKOsyVfew6BPw 
    youtube_channel_name: Data Science by Hadi

google_analytics: UA-169498675-1

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
